USE [master]
GO
/****** Object:  Database [KFHAssessment]    Script Date: 6/21/2026 2:33:32 PM ******/
CREATE DATABASE [KFHAssessment]
GO
ALTER DATABASE [KFHAssessment] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [KFHAssessment] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [KFHAssessment] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [KFHAssessment] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [KFHAssessment] SET ARITHABORT OFF 
GO
ALTER DATABASE [KFHAssessment] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [KFHAssessment] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [KFHAssessment] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [KFHAssessment] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [KFHAssessment] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [KFHAssessment] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [KFHAssessment] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [KFHAssessment] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [KFHAssessment] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [KFHAssessment] SET  ENABLE_BROKER 
GO
ALTER DATABASE [KFHAssessment] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [KFHAssessment] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [KFHAssessment] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [KFHAssessment] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [KFHAssessment] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [KFHAssessment] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [KFHAssessment] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [KFHAssessment] SET RECOVERY FULL 
GO
ALTER DATABASE [KFHAssessment] SET  MULTI_USER 
GO
ALTER DATABASE [KFHAssessment] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [KFHAssessment] SET DB_CHAINING OFF 
GO
ALTER DATABASE [KFHAssessment] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [KFHAssessment] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [KFHAssessment] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [KFHAssessment] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'KFHAssessment', N'ON'
GO
ALTER DATABASE [KFHAssessment] SET QUERY_STORE = ON
GO
ALTER DATABASE [KFHAssessment] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [KFHAssessment]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 6/21/2026 2:33:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
/****** Object:  Table [dbo].[AuditLogs]    Script Date: 6/21/2026 2:33:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AuditLogs](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[Action] [nvarchar](100) NOT NULL,
	[Entity] [nvarchar](100) NOT NULL,
	[EntityId] [int] NULL,
	[Detail] [nvarchar](1000) NULL,
	[OccurredAt] [datetime2](7) NOT NULL,
	[IpAddress] [nvarchar](50) NULL,
 CONSTRAINT [PK_AuditLogs] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Loans]    Script Date: 6/21/2026 2:33:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Loans](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ApplicantName] [nvarchar](100) NOT NULL,
	[LoanAmount] [decimal](18, 2) NOT NULL,
	[CreditScore] [int] NOT NULL,
	[Status] [int] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
	[CreatedByUserId] [int] NOT NULL,
 CONSTRAINT [PK_Loans] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 6/21/2026 2:33:33 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](100) NOT NULL,
	[Email] [nvarchar](200) NOT NULL,
	[PasswordHash] [nvarchar](500) NOT NULL,
	[Role] [nvarchar](50) NOT NULL,
	[IsActive] [bit] NOT NULL,
	[CreatedDate] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_AuditLogs_UserId]    Script Date: 6/21/2026 2:33:33 PM ******/
CREATE NONCLUSTERED INDEX [IX_AuditLogs_UserId] ON [dbo].[AuditLogs]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Loans_CreatedByUserId]    Script Date: 6/21/2026 2:33:33 PM ******/
CREATE NONCLUSTERED INDEX [IX_Loans_CreatedByUserId] ON [dbo].[Loans]
(
	[CreatedByUserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_Loans_Status]    Script Date: 6/21/2026 2:33:33 PM ******/
CREATE NONCLUSTERED INDEX [IX_Loans_Status] ON [dbo].[Loans]
(
	[Status] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Users_Email]    Script Date: 6/21/2026 2:33:33 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Users_Email] ON [dbo].[Users]
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
/****** Object:  Index [IX_Users_Username]    Script Date: 6/21/2026 2:33:33 PM ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Users_Username] ON [dbo].[Users]
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Loans]  WITH CHECK ADD  CONSTRAINT [FK_Loans_Users_CreatedByUserId] FOREIGN KEY([CreatedByUserId])
REFERENCES [dbo].[Users] ([Id])
GO
ALTER TABLE [dbo].[Loans] CHECK CONSTRAINT [FK_Loans_Users_CreatedByUserId]
GO
USE [master]
GO
ALTER DATABASE [KFHAssessment] SET  READ_WRITE 
GO
